# k8s/deployment.yaml
# k8s/deployment.yaml: Defines Kubernetes deployments for the backend, worker, and model services.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-backend
  template:
    metadata:
      labels:
        app: sentiment-backend
    spec:
      containers:
      - name: sentiment-backend
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/sentiment-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: sqs-secrets
              key: SQS_QUEUE_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-worker
  template:
    metadata:
      labels:
        app: sentiment-worker
    spec:
      containers:
      - name: sentiment-worker
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/sentiment-worker:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: sqs-secrets
              key: SQS_QUEUE_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-model
  template:
    metadata:
      labels:
        app: sentiment-model
    spec:
      containers:
      - name: sentiment-model
        image: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/sentiment-model:latest
        ports:
        - containerPort: 8080
